#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument.
#1-Accepts a string as an argument
#2-Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#3-Ping the IP 5 times

if [ "$#" -lt "1" ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping "$1" -c 5
fi
